### ISSUE TITLE
Android blank page

### ISSUE THREAD

**Issue by nihaonanshen** [txthinking/brook#138] opened 2018-01-15 08:48 UTC
#### Steps to deploy the server
0.
1.
2.

#### Steps to reproduce the problem
0.
1.
2.

**Comment by nihaonanshen** [comment] 2018-01-15 08:51
Android 8.1 installed after the main interface of a blank, there is no information, there have been such a situation before, but after reinstallation just fine, but this time unfortunately, I installed several times or not

**Comment by nihaonanshen** [comment] 2018-01-15 08:51
Android 8.1 installed after the main interface of a blank, there is no information, there have been such a situation before, but after reinstallation just fine, but this time unfortunately, I installed several times or not

**Comment by txthinking** [comment] 2018-01-15 08:59
When I open Brook Android in my Pixel first time, Blank page appeared.

I just swipe process and open again a few times. It shows correctly.

Try
* Wait a few seconds
* Swipe to quit app and open again

I am sorry I don't know the reason now.
If all guys encountered this situation are in China(can not connect firebase), maybe caused by  firebase SDK inside Brook Android.
If not, maybe another reason.

**Comment by txthinking** [comment] 2018-01-15 09:08
Anyone in unblocked firebase(sometimes unblocked google.com) network still encountered this problem?

**Comment by smbl64** [comment] 2018-01-15 09:30
I tried to pass my device's traffic through an http proxy (in WiFi settings) to unblock the Firebase. But I still see a blank page in the app.

**Comment by txthinking** [comment] 2018-01-15 09:53
I only have one Pixel phone. now I can't reproduce it.
If always show blank page. If urgently used please install the other version: https://github.com/txthinking/brook/releases
I am sorry.

I will try to find the reason, if anyone can provide some information. Thank you.
Sorry.

**Comment by smbl64** [comment] 2018-01-15 13:19
@txthinking 
Could you please provide list of changes in the Android client for the latest version?
I believe this will help in fixing the problem.

**Comment by chenhw2** [comment] 2018-01-15 13:37
Enable ```MIPS FPU Emulator``` to support Golang.

**Comment by txthinking** [comment] 2018-01-16 06:40
@smbl64 Just fixed #124  and upgrade much more dependencies.

**Comment by txthinking** [comment] 2018-01-16 06:41
@chenhw2 It looks like you want to comment #68 ?

**Comment by txthinking** [comment] 2018-01-18 07:59
Maybe solution: https://github.com/txthinking/brook/issues/139#issue-288811044
> 需要关闭，重新打开好几次才行。

Translate this sentence to English is: exit app and open again several times.

**Comment by txthinking** [comment] 2018-01-28 08:40
Please have a try this:
https://storage.googleapis.com/txthinking-file/_/tmp/brookapp-test-for-blank.apk

Thanks to all.

**Comment by xebex** [comment] 2018-01-28 12:09
@txthinking I'm using your newest apk file, but I still get a blank page every time when I open Brook. However, it does work immediately after I reboot my cellphone. But when I quit Brook and reopen it, the blank page shows again. BTW, my cellphone is Huawei Honor V8 with Android 7.0 (EMUI 5.0.1)

**Comment by txthinking** [comment] 2018-01-29 06:15
I built a version without firebase.
Can someone have a try please:

https://storage.googleapis.com/txthinking-file/_/tmp/brookapp-without-firebase.apk

**Comment by txthinking** [comment] 2018-01-29 08:07
Thank you.
Here is a no GMS version:
https://storage.googleapis.com/txthinking-file/_/tmp/brookapp-without-gms.apk

**Comment by txthinking** [comment] 2018-01-29 08:10
@TsFreddie Thank you very much. US, that means your network is not blocked. So this problem may not be related to firebase?

**Comment by TsFreddie** [comment] 2018-01-29 08:11
@txthinking thanks, but still blank. However, I found out if you switch dpi then switch to the app there's a great chance that the page shows up.

**Comment by txthinking** [comment] 2018-01-29 08:14
This max_aspect:2.1
https://storage.googleapis.com/txthinking-file/_/tmp/brookapp-max-dpi-without-gms.apk

**Comment by TsFreddie** [comment] 2018-01-29 08:17
@txthinking still the same. And yes, I don't think it is related to firebase nor gms.

**Comment by TsFreddie** [comment] 2018-01-29 09:00
@txthinking it is possible to move ```var R = require('superagent');``` into x-settings.html instead of it being in index.html?

**Comment by txthinking** [comment] 2018-01-30 01:55
@TsFreddie Yes, but I think this is another topic, please one issue one topic. Thanks.

**Comment by txthinking** [comment] 2018-01-30 01:55
Please try:

https://storage.googleapis.com/txthinking-file/_/tmp/brookapp-30a.apk
https://storage.googleapis.com/txthinking-file/_/tmp/brookapp-30b.apk

Thanks.

**Comment by TsFreddie** [comment] 2018-01-30 02:00
Both does not work. :(

**Comment by txthinking** [comment] 2018-02-01 11:31
Just ref: https://github.com/txthinking/brook/issues/146#issuecomment-362167783

**Comment by 973204** [comment] 2018-02-16 16:11
锤子手机m1l
6.0.1
白屏

**Comment by GeekHank** [comment] 2018-02-16 16:17
安卓白屏解决方案
点击进图程序白屏 按返回键一次回到桌面 再次打开即有界面 安卓通用 亲测小米6 lg g5 华为mate10

**Comment by kirbyzhu** [comment] 2018-02-18 09:11
还是没用 是不是还没解决啊？谷歌商店一直没有更新

**Comment by GeekHank** [comment] 2018-02-18 15:48
the solution to blank page打开白屏按返回键再次点开就好了

**Comment by kirbyzhu** [comment] 2018-02-18 16:31
不是的，还是白屏的可能性居多

**Comment by DoubleShift** [comment] 2018-02-27 12:08
补充下白屏的图
![e8595f17fca9a19391f01943feebb3b1](https://user-images.githubusercontent.com/5484152/36727883-d50515ac-1bf9-11e8-9019-c1187c22d367.jpg)
![6505ab1b63d0e1b8943ccbd5e543845e](https://user-images.githubusercontent.com/5484152/36727911-e3fa60e4-1bf9-11e8-9f4b-454ae5a6ff68.jpg)

**Comment by eyesinwind** [comment] 2018-03-04 11:12
安卓8.0打开后白屏，测试发现按返回键会到桌面的瞬间再按图标返回程序就可以显示界面，但是稍微晚一点返回程序反而会继续白屏。

**Comment by eyesinwind** [comment] 2018-03-04 11:18
On my Andriod 8.0, when you return this program immediately after you press HOME key , you will see the accout page, but if you delay a little bit for the return, probablly it will keep as blank page.

**Comment by txthinking** [comment] 2018-03-20 05:09
Copied from https://github.com/txthinking/brook/issues/146#issuecomment-362167783
> 感谢回复，我自己发现了个黑操作，小米自带的分屏任务，分屏运行brook，然后 点上面的结束分屏就可以全屏使用了。

**Comment by txthinking** [comment] 2018-03-22 07:31
Please help to test this two packages:

1: https://storage.googleapis.com/txthinking-file/_/Brook-dev-1.apk
2: https://storage.googleapis.com/txthinking-file/_/Brook-dev-2.apk

And share which version works.
Thanks.

**Comment by txthinking** [comment] 2018-03-24 09:35
I think this one will fix it 😬
https://storage.googleapis.com/txthinking-file/_/Brook-dev-3.apk

**Comment by TsFreddie** [comment] 2018-03-24 18:08
Brook-dev-3 works on my phone.

**Comment by smbl64** [comment] 2018-03-24 23:41
brook-dev-3 works for me as well

**Comment by duck531a98** [comment] 2018-03-25 11:56
brook-dev-3 works for me as well

**Comment by eyesinwind** [comment] 2018-03-27 08:38
brook-dev-3 works well on my Huawei P10 Android 8.0, thanks for the update!!

**Comment by xiaodd522** [comment] 2018-03-30 03:27
brook-dev-3 works for me as well, Samsung S9+ Android 8.0. Thank you!

**Comment by txthinking** [comment] 2018-03-31 05:34
Thanks.

Fixed in v20180401

**Closed by txthinking** 2018-03-31 05:34 UTC
Labels: android, bug
