### ISSUE TITLE
Google Play Error: Error retrieving information from server.[DF-DFERH-01]

### ISSUE THREAD

**Issue by hysonger** [txthinking/brook#516] opened 2019-02-22 10:10 UTC
### Prerequisites

* [x] Did you check the [wiki](https://github.com/txthinking/brook/wiki)?
* [x] Did you search in [issues](https://github.com/txthinking/brook/issues)?
Yes. There are some issues about the failure of using Google Play, but they seem to be unable to solve the problem.
* [x] Are you running the latest version?
Yes. All the server and client programs are the version of v20190205.
* [x] I will write this according to this template.
* [x] I will write this in English.
Yes, but my English is not good:D

### Environment

* Brook Version: v20190205
* Server Operating System: Debian Linux
* Server Operating System Version: 9.0
* Server Operation System Language: English
* Client Operating System: EMUI based on Android
* Client Operating System Version: 9.0
* Client Operation System Language: Simplified Chinese

### Expected Behavior
Google Play should be available to use after connecting the Brook Server.
### Current Behavior
Google Play failed to connect. 
### Steps to Reproduce

1.Install Brook Android app and set the server information.
2.Tap the button to connect.
3.Open the Play Store app.

### Detailed Description
The Play Store app reported an error:
从服务器检索信息时出错。(Error retrieving information from server.)[DF-DFERH-01]。
However, the browser can normally visit Google at the same time, which proves that the Brook connection has successfully built. 
### Possible Solution
Using the global mode in Brook Android app could solve the problem. According to some articles online, in China mainland, Google Play Service tries to connect to *services.googleapis.cn*, which is resolved to the IP of Google China. Redirecting this link to the correct server might be the key to the problem.

**Comment by Snail404** [comment] 2019-02-23 06:21
man, I have the same issue with you, using SS free service can connect to the server, but speed is extremely slow, since it's free, it must be many people using it

**Comment by txthinking** [comment] 2019-02-24 04:14
*Is services.googleapis.cn <http://services.googleapis.cn> blocked(DNS, IP
TCP, UDP) in China?*

**Comment by hysonger** [comment] 2019-02-25 15:54
maybe the Google Play in China will be opened soon, so they replaced the address :D

**Comment by Snail404** [comment] 2019-02-27 02:10
thinking too much, lol

**Comment by PokemonWei** [comment] 2019-02-27 04:51
I have the same problem.I can use google,but can not google play on Android

**Comment by xiaofdejimo** [comment] 2019-03-10 14:13
same problem, but is only failed on 20190205. I reinstall the version 20181212, the problem gone. so it must be something wrong with 20190205.

**Comment by wwwang95** [comment] 2019-03-13 03:33
> same problem, but is only failed on 20190205. I reinstall the version 20181212, the problem gone. so it must be something wrong with 20190205.

same to you

**Comment by Snail404** [comment] 2019-04-04 08:43
Issue fixed, IDK why, lol
Honor View 10, EMUI 9.0.0.182

**Comment by txthinking** [comment] 2019-05-05 05:24
In white mode[0], any *.cn domain[1] will be resolved by China DNS server, and If the result IP is in the white_cidr list[2], then connect it directly.

0: https://github.com/txthinking/brook/wiki/Mode-in-Brook-GUI-client
1: `cn` is in https://github.com/txthinking/blackwhite/blob/master/white.list
2: https://github.com/txthinking/blackwhite/blob/master/white_cidr.list

**Comment by txthinking** [comment] 2019-12-20 03:27
Does anyone ensure this caused by services.googleapis.cn?

**Comment by txthinking** [comment] 2020-08-04 12:43
I googled found this may google play case.

**Closed by txthinking** 2020-08-04 12:43 UTC
