### ISSUE TITLE
Android stop VPN automatically

### ISSUE THREAD

**Issue by mariokart1992** [txthinking/brook#103] opened 2017-11-12 02:54 UTC
My device is OnePlus 5 system is OOS 4.5.14(7.1.1)

The app version is the newest one in Google play

After I used the app for about 1-2 hours ,the VPN automatically stopped . First of all I checked the Background whitelist ,I am sure about the Brook is in it.Then I check the VPN setting ,I have set Brook to be the always use VPN.

However, the issue still happen every 1-2 hours.

**Comment by txthinking** [comment] 2017-11-12 06:13
This may be caused by OnePlus custom ROM.
http://www.oneplusbbs.com/thread-3208649-1-1.html

Because it has been running for 24+ hours on my Pixel, no background whitelist, no extra configuration.

**Comment by txthinking** [comment] 2017-11-12 09:06
You said the VPN automatically stopped, can you provide much more information about `stopped`, VPN(key) logo still there?

**Comment by mariokart1992** [comment] 2017-11-12 23:41
The VPN key logo disappeared. When I use SS the issue never happened. Thanks so much for your reply. China 's network is annoying.

**Comment by Portan** [comment] 2017-11-15 15:01
This is probably because your system cleaning process, you need to make this app alive in background.

**Comment by txthinking** [comment] 2018-01-13 03:00
I just close it, because this is caused by your customize OS.

**Closed by txthinking** 2018-01-13 03:00 UTC
